let AllWatchDatas = [
    {
        id: 1,
         img: 'images/Watch/9-95023_rolex-watch-png-transparent-image-rolex-submariner-rolex-removebg-preview-min.png',
         watchName: 'رولکس اکسپلورر',
         colors: '⚪',
         colorName: 'white',
         sizes: '22 , 25',
         price: '12000000',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '12',
         numOfSales: '122',
    },
    {
        id: 2,
         img: 'images/Watch/automatic-watch-rolex-watch-strap-gold-watches-rolex-watches-female-form-removebg-preview-min.png',
         watchName: 'رولکس سابمارینر',
         colors: '⚫',
         colorName: 'black',
         price: '20000000',
         sizes: '20 , 24',
         bandModel: 'چرمی , فلزی',
         glasesModel: 'مینرال',
         numOfColor: '1',
         availableQuantity: '25',
         numOfSales: '21',
    },
    {
        id: 3,
         img: 'images/Watch/download-removebg-preview-min.png',
         watchName: 'رولکس دیت‌جاست',
         colors: '🟡 ⚫',
         colorName: 'yellow',
         colorName2: 'black',
         price: '25000000',
         sizes: '19 , 29',
         bandModel: 'چرمی',
         glasesModel: 'کریستال , مینرال',
         numOfColor: '2',
         availableQuantity: '5',
         numOfSales: '45',
    },
    {
        id: 4,
         img: 'images/Watch/m228236-0012_drp-upright-bba-with-shadow-removebg-preview-min.png',
         watchName: 'رولکس دیت‌جاست ۲',
         colors: '⚪ 🟡',
         colorName: 'white',
         colorName2: 'yellow',
         price: '17500000',
         sizes: '18 , 19 , 21',
         bandModel: 'ناتو , چرمی',
         glasesModel: 'اکریلیک',
         numOfColor: '2',
         availableQuantity: '9',
         numOfSales: '52',
    },
    {
        id: 5,
         img: 'images/Watch/m228239-0033_drp-upright-bba-with-shadow-removebg-preview-min.png',
         watchName: 'رولکس یاخ ‌مستر',
         colors: '⚫',
         colorName: 'black',
         price: '19900000',
         sizes: '20 , 21',
         bandModel: 'ناتو',
         glasesModel: 'اکریلیک , مینرال',
         numOfColor: '1',
         availableQuantity: '47',
         numOfSales: '234',
    },
    {
        id: 6,
         img: 'images/Watch/rolex_datejust_36mm_16233_w524192_e9a8b19212-w1242.jpg.auto-removebg-preview-min.png', watchName: 'رولکس یاخ مستر ۲',
         colors: '⚪',
         colorName: 'white',
         price: '220000000',
         sizes: '25',
         bandModel: 'سیلیکونی',
         glasesModel: 'مینرال',
         numOfColor: '1',
         availableQuantity: '2',
         numOfSales: '32',
    },
    {
        id: 7,
         img: 'images/Watch/rolex-datejust-rolex-daytona-watch-rolex-gmt-master-ii-silver-rolex-watch-watches-female-form-removebg-preview-min.png',
         watchName: 'رولکس دیپ‌سی‌',
         colors: '🟤 ⚪ ⚫',
         colorName: 'white',
         colorName2: 'black',
         colorName3: 'orange',
         price: '72000000',
         sizes: '20',
         bandModel: 'چرمی , ناتو',
         glasesModel: 'کریستال',
         numOfColor: '3',
         availableQuantity: '12',
         numOfSales: '70',
    },
    {
        id: 8,
         img: 'images/Watch/rolex-datejust-rolex-submariner-watch-rolex-sea-dweller-rolex-watch-male-table-removebg-min.png',
         watchName: 'رولکس GMT مَستر ',
         colors: '🟡 🟤',
         colorName: 'yellow',
         colorName2: 'orange',
         price: '1000000',
         sizes: '22 , 24',
         bandModel: 'فلزی , چرمی , ناتو',
         glasesModel: 'کریستال',
         numOfColor: '2',
         availableQuantity: '55',
         numOfSales: '57',
    },
    {
        id: 9,
         img: 'images/Watch/rolex-submariner-no-date-114060-ceramic-bezel-mens-watch-880965-removebg-preview-min.png',
         watchName: 'رولکس طلایی',
         colors: '⚪ 🟤',
         colorName: 'white',
         colorName2: 'orange',
         price: '35900000',
         sizes: '19',
         bandModel: 'سیلیکونی',
         glasesModel: 'نشکن',
         numOfColor: '2',
         availableQuantity: '23',
         numOfSales: '27',
    },
    {
        id: 10,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
    {
        id: 11,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
    {
        id: 12,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
    {
        id: 13,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
    {
        id: 14,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
    {
        id: 15,
         img: 'images/Watch/png-transparent-rolex-daytona-rolex-datejust-watch-rolex-oyster-rolex-watch-accessory-gold-steel-removebg-preview-min.png',
         watchName: 'رولکس پلاتینیومی',
         colors: '⚫',
         colorName: 'black',
         price: '98000000',
         sizes: '12',
         bandModel: 'چرمی',
         glasesModel: 'کریستال',
         numOfColor: '1',
         availableQuantity: '4',
         numOfSales: '25',
    },
]

export default AllWatchDatas